language: go

go_import_path: github.com/songgao/water
install: go get -u golang.org/x/lint/golint
script: make ci

matrix:
  include:
    - os: linux
      dist: xenial
      go: 1.12.1
    - os: linux
      dist: xenial
      go: 1.10.8
    - os: osx
      go: 1.12.1
    - os: osx
      go: 1.10.8
